language: go

go:
   - 1.0
   - 1.1
   - 1.2
   - 1.3
   - 1.4
   - 1.5
   - tip

install:
   - mv $GOPATH/src/github.com/MorpheusXAUT $GOPATH/src/github.com/morpheusxaut
   - go get -v ./...

script:
   - go build -v ./...
   - go test -v ./...

matrix:
  allow_failures:
      - go: 1.0
      - go: 1.1